### ISSUE TITLE
IO not detected

### ISSUE THREAD

**Issue by JayanthSuresh** [sdurbin-pxc/plcnext-io-drivers-cpp#1]
PLC: AXC F 2152

I/O: 

2702071 - AXL F DI8/3 DO8/3 2H
2702072 - AXL F AI2 AO2 1H

PLC Firmware: 2019.6.3

SDK: 2019.6.3

I have the driver up and running. The RUN and D are solid green on the PLC.

The IO modules have Solid green for 'D'.

When I run the SimpleApplication example code from github, it appears that it is unable to find any IO modules attached. Do you know what might be causing this ?

vector modules = axio.getModules();

modules.size() is returning '0'.

**Comment by sdurbin-pxc** [comment]
Hello,

That firmware/io/sdk should be fine together.

Is the `axio.isInitialized()` function returning `true`?

Also, can you tell me what the diagnostic info is returning:

`AXC2152::DiagnosticsInfo diag = axio.getDiagnosticsInfo();`

Specifically, `diag.status`.

Thanks,
Steve

**Comment by sdurbin-pxc** [comment]
Hello Jayanth,

Are you still having this problem?

**Comment by JayanthSuresh** [comment]
Hi Steven,
The issue still exists. I upgraded the firmware to 2019.9 and was testing the C++ library import on the PLCNext Engineer.  Since the IO Driver is not tested for the 2019.9, I didn't get a chance to test.  
I will revert back the firmware to 2019.6 and test it with the IO driver and share the diagnostic data.
Thanks for following up.

**Comment by sdurbin-pxc** [comment]
I would stick with 2019.9.  I will be updating the io-driver component to support 2019.9 very soon (hopefully today).

**Comment by JayanthSuresh** [comment]
Sounds good!
I will test it out when the io-driver component support for 2019.9 is released and update you with the status.
Thanks,

**Comment by JayanthSuresh** [comment]
I tested the io-driver component. I still have the same issue.

I/O: 
2702071 - AXL F DI8/3 DO8/3 2H
2702072 - AXL F AI2 AO2 1H

FW: 2019.9
SDK: 2019.9
io-driver component: 2019.9

`!axio.isInitialized()` returns `1`

`diag.status` returns `224` before and after `vector<AXLModule*> modules = axio.getModules();`

**Comment by sdurbin-pxc** [comment]
Hi Jayanth,

diag.status looks fine (0xE0).

A few troubleshooting questions:

- Do the I/O modules have solid green lights?
- Are the bus adapters on the controller and the back of each module connected?
- Is there any way you can post your code so I can look at it?  (pastebin, etc)?

Thanks,
Steve

**Comment by JayanthSuresh** [comment]
Steve,

- The I/O modules have solid green lights
- The Bus adapters are in place. I was able to test these modules with the same setup using the PLCNext Engineer with structured text.
- I am using your SimpleApplication example code.

**Comment by sdurbin-pxc** [comment]
Jayanth,

I would try resetting the device to factory (retains 2019.9 firmware), reinstalling the I/O driver component and try again.  Quite possibly the PLCnext Engineer project setup is interfering in some way.

To reset the device: 

_sudo recover-plcnext 1_

**Comment by JayanthSuresh** [comment]
Steve,

I did a reset by executing `sudo recover-plcnext 1`. I reinstalled the I/O driver component and ran the program. The I/O has a solid green light. The RUN and D lights are solid on the controller.

The `diag.status` is (0xE0) and is still unable to detect either of the two modules. 

`axio.isInitialized()` returns `true`

**Comment by sdurbin-pxc** [comment]
Just for clarification:

axio.isInitialized() is true
or
!axio.isInitialized() is true?

**Comment by JayanthSuresh** [comment]
sorry for the typo, `axio.isInitialized()` returns `true`.
