### ISSUE TITLE
AXLF_SE_DO16 SetValue not holding 

### ISSUE THREAD

**Issue by kirant400** [sdurbin-pxc/plcnext-io-drivers-cpp#2]
Hi, 
I am using the firmware 
axcf2152-mingw_sdk-2024.0.0_LTS-24.0.0.102
PLC: axcf2152

After setValue and WriteOutput given below:
```c
do16->channel[0]->setValue(true);
axio.writeOutputs();
``` 

Immediately the Output is getting the value as false. It does not hold the last set value.

<details><summary>Details</summary>
<p>

Initializing Axioline bus system...
Pre-init diag status: E0, Param1: 0, Param2: 0
Bus is active.
Scanning Modules!
module type found: 1d19
serial: 1367235053
order: 1088129
hardware ver: 0000-00-00 : 01
firmware ver: 0000-00-00 : 1.00
module type found: 1d18
serial: 1366564523
order: 1088127
hardware ver: 0000-00-00 : 01
firmware ver: 0000-00-00 : 1.00
module type found: 531005
module type found: 1a0d
serial: 1366481507
order: 1088104
hardware ver: 0000-00-00 : 01
firmware ver: 0000-00-00 : 1.00
Axio class instantiated.

Scanning I/O modules...
Axioline bus initialized.

</p>
</details>

**Comment by sdurbin-pxc** [comment]
Hello.

If you are running a PLCnext Engineer project with I/O configured, you will not be able to write the outputs via these I/O drivers.  You can read and configure the I/O, but every process cycle the PLCnext Engineer runtime will overwrite the output process data. You can test this by stopping the plcnext runtime via "/etc/init.d/plcnext stop" and see if your outputs are working.  Feel free to reach out to me at  my sd****n@phoenixcontact.com email address.

**Comment by kirant400** [comment]
Thank you very much.  After stopping the PLCNext, It is working as expected. 
I will remove it from startup permanently.
